
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=UTC&useLegacyDate
    username: postgres
    password: gaucho
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update